version: "3"
services:
    app:
        image: pihole/pihole:latest
        container_name: pihole
        env_file: .env
        networks:
            - gateway
        ports:
            - 53:53/tcp
            - 53:53/udp
        volumes:
            - conf:/etc/pihole
            - dnsmasq:/etc/dnsmasq.d
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.entrypoints=http"
            - "traefik.http.routers.pihole.rule=Host(`pihole.localhost`)"
            - "traefik.http.routers.pihole.service=pihole"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"
        restart: unless-stopped

networks:
    gateway:
        name: gateway
        external: true

volumes:
    conf:
        labels:
            keep: ""
    dnsmasq:
        labels:
            keep: ""